use anyhow::{bail, Context, Result};
use serde::Deserialize;
use std::path::Path;

/// Minimal VS Code multi-root workspace JSON subset.
#[derive(Debug, Deserialize)]
struct CodeWorkspace {
    folders: Vec<CodeFolder>,
}

#[derive(Debug, Deserialize)]
struct CodeFolder {
    #[serde(default)]
    name: Option<String>,
    path: String,
}

pub fn default_repoly_toml() -> &'static str {
    r#"# repoly.toml — multi-repo workspace for the repoly CLI
# https://github.com/bryntje/repoly
schema_version = 1

[workspace]
name = "my-workspace"

[context]
# Paths relative to this file's directory (workspace root)
always = []
# status_doc = "docs/STATUS.md"
max_chars = 48000

[[repos]]
id = "api"
path = "./api"
role = "api"
tags = ["backend"]
description = "API service"

[[repos]]
id = "web"
path = "./web"
role = "frontend"
tags = ["frontend"]
depends_on = ["api"]
description = "Web app"
"#
}

pub fn repoly_toml_from_code_workspace(raw: &str, ws_path: &Path) -> Result<String> {
    let parsed: CodeWorkspace =
        serde_json::from_str(raw).context("invalid .code-workspace JSON")?;
    if parsed.folders.is_empty() {
        bail!("code-workspace has no folders");
    }

    let mut out = String::new();
    out.push_str("# Generated by `repoly init --from-code-workspace`\n");
    out.push_str(&format!(
        "# Source: {}\n",
        ws_path
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap_or("workspace")
    ));
    out.push_str("schema_version = 1\n\n");
    out.push_str("[workspace]\n");
    let name = ws_path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("workspace")
        .to_lowercase()
        .replace(' ', "-");
    out.push_str(&format!("name = \"{name}\"\n\n"));
    out.push_str("[context]\n");
    out.push_str("always = []\n");
    out.push_str("max_chars = 48000\n\n");

    let mut used_ids = std::collections::HashSet::new();
    for folder in &parsed.folders {
        let base = folder.name.clone().unwrap_or_else(|| {
            Path::new(&folder.path)
                .file_name()
                .and_then(|s| s.to_str())
                .unwrap_or("repo")
                .to_string()
        });
        let mut id = slugify(&base);
        if id.is_empty() {
            id = "repo".into();
        }
        // Ensure unique
        let mut candidate = id.clone();
        let mut n = 2;
        while !used_ids.insert(candidate.clone()) {
            candidate = format!("{id}-{n}");
            n += 1;
        }
        id = candidate;

        out.push_str("[[repos]]\n");
        out.push_str(&format!("id = \"{id}\"\n"));
        // Keep path as written in the workspace file (relative paths preferred)
        let path_escaped = folder.path.replace('\\', "\\\\").replace('"', "\\\"");
        out.push_str(&format!("path = \"{path_escaped}\"\n"));

        let (role, tags) = infer_role_and_tags(&base, &folder.path);
        if let Some(r) = role {
            out.push_str(&format!("role = \"{r}\"\n"));
        }
        if !tags.is_empty() {
            let tags_str = tags
                .iter()
                .map(|t| format!("\"{t}\""))
                .collect::<Vec<_>>()
                .join(", ");
            out.push_str(&format!("tags = [{tags_str}]\n"));
        }

        if let Some(name) = &folder.name {
            out.push_str(&format!("description = \"{name}\"\n"));
        }
        out.push('\n');
    }

    Ok(out)
}

pub(crate) fn infer_role_and_tags(name: &str, path: &str) -> (Option<String>, Vec<String>) {
    let n = name.to_lowercase();
    let p = path.to_lowercase();

    let mut role = None;
    let mut tags = Vec::new();

    if n.contains("api") || n.contains("core") || p.contains("core") {
        role = Some("api".to_string());
        tags.extend(vec!["backend".to_string(), "api".to_string()]);
    } else if n.contains("web")
        || n.contains("app")
        || n.contains("dashboard")
        || n.contains("frontend")
    {
        role = Some("frontend".to_string());
        tags.extend(vec!["frontend".to_string()]);
    } else if n.contains("bot") || n.contains("discord") {
        role = Some("bot".to_string());
        tags.extend(vec!["bot".to_string(), "discord".to_string()]);
    } else if n.contains("agent") || n.contains("hermit") || n.contains("mind") {
        role = Some("agent".to_string());
        tags.extend(vec!["agent".to_string(), "skills".to_string()]);
    } else if n.contains("lib") || n.contains("styling") || n.contains("ui") {
        role = Some("lib".to_string());
        tags.extend(vec!["lib".to_string(), "ui".to_string()]);
    } else if n.contains("meta") || n.contains("docs") {
        role = Some("meta".to_string());
        tags.extend(vec!["docs".to_string(), "meta".to_string()]);
    }

    if n.contains("auth") || n.contains("identity") || n.contains("login") {
        tags.push("auth".to_string());
    }
    if n.contains("payment") || n.contains("mollie") {
        tags.push("payments".to_string());
    }
    if n.contains("memory") || n.contains("vault") {
        tags.push("memory".to_string());
    }

    (role, tags)
}

pub(crate) fn slugify(s: &str) -> String {
    let lower = s.to_lowercase();
    let mut out = String::new();
    let mut prev_dash = false;
    for c in lower.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c);
            prev_dash = false;
        } else if !prev_dash && !out.is_empty() {
            out.push('_');
            prev_dash = true;
        }
    }
    // ids must start with a letter
    let trimmed = out.trim_matches('_').to_string();
    if trimmed.is_empty() {
        return String::new();
    }
    if trimmed.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        format!("r_{trimmed}")
    } else {
        trimmed
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn imports_code_workspace() {
        let json = r#"{
          "folders": [
            { "name": "META", "path": "./Innersync-meta" },
            { "name": "CORE", "path": "./Innersync_Core" }
          ]
        }"#;
        let s =
            repoly_toml_from_code_workspace(json, Path::new("Innersync.code-workspace")).unwrap();
        assert!(s.contains("id = \"meta\""));
        assert!(s.contains("path = \"./Innersync-meta\""));
        assert!(s.contains("id = \"core\""));
    }

    #[test]
    fn slugify_basic() {
        assert_eq!(slugify("Alphapy-Dashboard"), "alphapy_dashboard");
        assert_eq!(slugify("INNERSYNC_STYLING"), "innersync_styling");
    }
}

#[cfg(test)]
mod infer_tests {
    use super::*;

    #[test]
    fn infers_api_role() {
        let (role, tags) = infer_role_and_tags("Core API", "./Innersync_Core");
        assert_eq!(role, Some("api".to_string()));
        assert!(tags.contains(&"backend".to_string()));
    }

    #[test]
    fn infers_agent_role() {
        let (role, _tags) = infer_role_and_tags("Hermit", "./Hermit");
        assert_eq!(role, Some("agent".to_string()));
    }
}
